#!/bin/bash
#
#

gnuplot <<EOF
set terminal pngcairo size 1280,720
set output 'logfile.png'
set y2range [ -0.2 : * ]
set autoscale y2max 

set y2tics 0,1
set ytics nomirror

#set style line 1 lc rgb '#8b1a0e' pt 1 ps 1 lt 1 lw 4
#set style line 2 lc rgb '#5e9c36' pt 6 ps 1 lt 1 lw 4

plot 'logfile.txt' using 1:(\$2-0.1) with steps title 'Worker threads' axis x1y2 lc rgb '#3498db' lw 1, \
	'logfile.txt' using 1:3 with lines title 'Max temp' lc rgb '#c0392b' lw 2, \
	'logfile.txt' using 1:4 with lines title 'Avg temp' lc rgb '#f1c40f' lw 2

EOF
